[book]
authors = ["Herumb Shandilya"]
language = "en"
multilingual = false
src = "src"
title = "A Small Book on Information Retrieval"
description = "Diving into Information Retrieval and ColBERT"

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "light"